import type { Metadata } from "next";
import { Inter, Montserrat, Sofia } from "next/font/google";
import "./globals.css";
import ParticleCanvas from "@/components/home/Background";
import { Navbar } from "@/components/navbar/navbar";
import { ThemeProvider } from "@/components/providers/theme-provicer";
import { ModeToggle } from "@/components/home/mode-toggle";

const montserrat = Montserrat({ subsets: ["latin"] });

const sofia = Sofia({
  weight: ["400"],
  variable: "--sofia",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest"></link> */}
      <body
        className={`${montserrat.className} ${sofia.variable} h-full w-full overflow-hidden`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <ParticleCanvas />
          <ModeToggle />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
